# Generated by Django 4.2.8 on 2023-12-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_url', models.CharField(max_length=500)),
                ('vmix_url', models.CharField(max_length=500)),
                ('replay_start_recording_interval', models.IntegerField(default=2)),
                ('replay_set_speed_value', models.FloatField(default=0.8)),
                ('replay_export_switch', models.BooleanField(default=True)),
                ('check_interval', models.IntegerField(default=1)),
                ('sleep_duration', models.IntegerField(default=10)),
                ('sleep_window_input', models.IntegerField(default=16)),
                ('homepen1num_input', models.IntegerField(default=10)),
                ('homepen2num_input', models.IntegerField(default=15)),
                ('awaypen1num_input', models.IntegerField(default=13)),
                ('awaypen2num_input', models.IntegerField(default=14)),
                ('quickplay_input', models.IntegerField(default=15)),
            ],
        ),
    ]
