# Generated by Django 4.2.8 on 2023-12-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0002_settings_export_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
